"""Phantomline footage library route.

Surfaces the curated stock footage manifest (static/library/footage-manifest.json)
to the studio UI so users can browse + pick clips that ship with the install
to use as the rolling visual layer in their videos.

The manifest itself is generated by `_compress_footage.py` (one-off content
prep tool). Files live in Supabase Storage at the URLs the manifest points to;
the desktop install lazily downloads + caches them in
`output/footage-cache/<clip_id>.mp4` on first use.

Endpoints:
  GET /api/library/footage              -> full manifest (cached client-side)
  GET /api/library/footage?aspect=9:16  -> filter by aspect ratio
  GET /api/library/footage?category=X   -> filter by category tag
  GET /api/library/footage/<clip_id>    -> single clip entry

This is read-only by design — the studio doesn't need to upload to the
library, just consume it. Library curation happens at content-prep time
(Kyle adds clips to Supabase + bumps manifest, ships in next release).
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from flask import Blueprint, jsonify, request

from core import BASE_DIR


library_bp = Blueprint("library", __name__)

MANIFEST_PATH = Path(BASE_DIR) / "static" / "library" / "footage-manifest.json"


def _load_manifest() -> dict[str, Any]:
    """Read the footage manifest from disk on every request. The file is
    small (~3 KB for 19 clips) and rarely changes, so the disk hit is
    negligible — and we get fresh data without a server restart when the
    manifest is updated by `_compress_footage.py` or hand-edited."""
    if not MANIFEST_PATH.exists():
        return {"version": 1, "clip_count": 0, "clips": []}
    try:
        return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        # Don't 500 on a malformed manifest — return an empty library so the
        # picker UI shows "No footage available" instead of crashing.
        return {"version": 1, "clip_count": 0, "clips": [], "error": str(exc)}


@library_bp.route("/api/library/footage", methods=["GET"])
def api_library_footage():
    """Return the footage manifest, optionally filtered by aspect or category.

    Filters are AND-combined so ?aspect=9:16&category=horror returns clips
    tagged horror at 9:16 only. Filters are applied case-insensitively for
    forgiveness (categories are user-edited so "Horror" and "horror" should
    both match a query for ?category=horror)."""
    manifest = _load_manifest()
    clips = manifest.get("clips") or []

    aspect = (request.args.get("aspect") or "").strip().lower()
    category = (request.args.get("category") or "").strip().lower()

    if aspect:
        clips = [c for c in clips if (c.get("aspect_ratio") or "").lower() == aspect]
    if category:
        clips = [
            c for c in clips
            if any(category == (cat or "").strip().lower() for cat in (c.get("categories") or []))
        ]

    return jsonify({
        "ok": True,
        "version": manifest.get("version", 1),
        "clip_count": len(clips),
        "clips": clips,
    })


@library_bp.route("/api/library/footage/<clip_id>", methods=["GET"])
def api_library_footage_one(clip_id: str):
    """Return a single clip by id (e.g. 'demo-02'). Useful when the studio
    has a saved-project reference and needs to re-resolve metadata at render
    time without fetching the full manifest."""
    manifest = _load_manifest()
    for c in manifest.get("clips") or []:
        if c.get("id") == clip_id:
            return jsonify({"ok": True, "clip": c})
    return jsonify({"ok": False, "error": "Clip not found"}), 404
